version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Paris"
      time: "06:00"
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
