version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - ":game_die: dependencies"
      - ":robot: bot"
    automerged_updates:
      - match:
          dependency_name: "github.com/portapps/portapps"